name: 🔓 美人鱼 Laravue QA

on: [pull_request]

jobs:
  run-ci:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Automated Machine
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check test works
        run: npm test